// AUTO-GENERATED by scripts/upload-cards-to-blob.ts — do not edit by hand.
// Maps pack-type slug → Vercel Blob public URL.

export const PACK_ART_URLS: Record<string, string> = {
  "animal_only": "https://gefpu2qdpingvpmy.public.blob.vercel-storage.com/cards/packs/animal_only.png",
  "basic": "https://gefpu2qdpingvpmy.public.blob.vercel-storage.com/cards/packs/basic.png",
  "mythic": "https://gefpu2qdpingvpmy.public.blob.vercel-storage.com/cards/packs/mythic.png",
  "pokemon_only": "https://gefpu2qdpingvpmy.public.blob.vercel-storage.com/cards/packs/pokemon_only.png",
  "premium": "https://gefpu2qdpingvpmy.public.blob.vercel-storage.com/cards/packs/premium.png"
};
